# Question.all.destroy_all

question_1 = Question.create(question: "How many languages has Harry Potter been translated into?" )
question_2 = Question.create(question: "Where is the oldest tree in the world?")
question_3 = Question.create(question: "What colour do 75% of all nations flag contain?")
question_4 = Question.create(question: "From 1919 to 1933, the Weimar Republic was the government in which country?")
question_5 = Question.create(question: "What part of a sailboat does the tiller move?")
question_6 = Question.create(question: "Caravaggio shared a first name with what other famous artist?")
question_7 = Question.create(question: "Which of these was the first actor to be paid $1 million for a role, for Bridge on the River Kwai?")
question_8 = Question.create(question: "What body of water did the Romans call mare nostrum?")
question_9 = Question.create(question: "Which of these is the hardest mineral on Earth?")
question_10 = Question.create(question: "A crepuscular animal becomes active at what time?")
question_11 = Question.create(question: "Ken Thompson and Dennis Ritchie co-created which operating system?")

# CorrectAnswer.all.destroy_all

CorrectAnswer.create(answer: "68", question_id: question_1.id)
CorrectAnswer.create(answer: "California", question_id: question_2.id)
CorrectAnswer.create(answer: "Red", question_id: question_3.id)
CorrectAnswer.create(answer: "Germany", question_id: question_4.id)
CorrectAnswer.create(answer: "The rudder", question_id: question_5.id)
CorrectAnswer.create(answer: "Michelangelo", question_id: question_6.id)
CorrectAnswer.create(answer: "William Holden", question_id: question_7.id)
CorrectAnswer.create(answer: "The mediterranean Sea", question_id: question_8.id)
CorrectAnswer.create(answer: "Diamond", question_id: question_9.id)
CorrectAnswer.create(answer: "Dusk", question_id: question_10.id)
CorrectAnswer.create(answer: "Unix", question_id: question_11.id)

# IncorrectAnswer.all.destroy_all

IncorrectAnswer.create(answer: "75", question_id: question_1.id)
IncorrectAnswer.create(answer: "46", question_id: question_1.id)
IncorrectAnswer.create(answer: "52", question_id: question_1.id)
IncorrectAnswer.create(answer: "Oxfordshire", question_id: question_2.id)
IncorrectAnswer.create(answer: "Australia", question_id: question_2.id)
IncorrectAnswer.create(answer: "Mumbai", question_id: question_2.id)
IncorrectAnswer.create(answer: "Blue", question_id: question_3.id)
IncorrectAnswer.create(answer: "White", question_id: question_3.id)
IncorrectAnswer.create(answer: "Yellow", question_id: question_3.id)
IncorrectAnswer.create(answer: "Austria", question_id: question_4.id)
IncorrectAnswer.create(answer: "Switzerland", question_id: question_4.id)
IncorrectAnswer.create(answer: "Norway", question_id: question_4.id)
IncorrectAnswer.create(answer: "The compass", question_id: question_5.id)
IncorrectAnswer.create(answer: "The Hull", question_id: question_5.id)
IncorrectAnswer.create(answer: "The Sails", question_id: question_5.id)
IncorrectAnswer.create(answer: "Jackson Pollock", question_id: question_6.id)
IncorrectAnswer.create(answer: "Hieronymous Bosch", question_id: question_6.id)
IncorrectAnswer.create(answer: "Pieter Brueghel the Elder", question_id: question_6.id)
IncorrectAnswer.create(answer: "Gary Cooper", question_id: question_7.id)
IncorrectAnswer.create(answer: "James Stewart", question_id: question_7.id)
IncorrectAnswer.create(answer: "John Wayne", question_id: question_7.id)
IncorrectAnswer.create(answer: "The Irish Sea", question_id: question_8.id)
IncorrectAnswer.create(answer: "The black sea", question_id: question_8.id)
IncorrectAnswer.create(answer: "The Atlantic Ocean", question_id: question_8.id)
IncorrectAnswer.create(answer: "Silver", question_id: question_9.id)
IncorrectAnswer.create(answer: "Lead", question_id: question_9.id)
IncorrectAnswer.create(answer: "Titanium", question_id: question_9.id)
IncorrectAnswer.create(answer: "Dawn", question_id: question_10.id)
IncorrectAnswer.create(answer: "Midday", question_id: question_10.id)
IncorrectAnswer.create(answer: "Late night", question_id: question_10.id)
IncorrectAnswer.create(answer: "Debian", question_id: question_11.id)
IncorrectAnswer.create(answer: "Ubunutu", question_id: question_11.id)
IncorrectAnswer.create(answer: "Windows", question_id: question_11.id)